In [8]:
import csv
import time, os, sys, re #basics
import zipfile, json, datetime, string 
import matplotlib.pyplot as plt
import numpy as np #basic math
from statistics import * #stats
import pandas as pd
from pandas.io.formats.style import Styler

nba=pd.read_csv('nbaPO.csv') #read it in  ; or full path: '/content/ex1.csv'

#nba.columns
nba
# nba.plot(kind='scatter', y='FT%', x='Age')
pd.crosstab(nba["Pos"], nba["AST"]) #too many numbers for a crosstab!
#pd.crosstab(nba["Pos"], nba["PTS"])
#pd.crosstab(nba[])


#nba.hist(figsize=(12,8))

AST,0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,6.2,6.3,6.4,6.5,6.7,6.8,7.0,8.3,8.6,9.8
Pos,,,,,,,,,,,,,,,,,,,,,
C,6,1,2,2,3,4,2,2,3,0,...,0,0,0,0,0,0,0,0,0,0
PF,9,1,1,2,3,1,0,3,4,2,...,0,2,0,0,0,1,0,0,0,0
PG,2,0,0,1,1,2,1,1,1,2,...,0,1,1,1,1,0,0,1,0,1
SF,4,1,1,3,2,5,3,1,2,0,...,2,0,0,0,0,0,1,0,0,0
SG,6,0,0,4,6,1,2,1,0,1,...,0,0,0,0,0,0,0,0,1,0

In [10]:
import csv
import time, os, sys, re #basics
import zipfile, json, datetime, string 
import matplotlib.pyplot as plt
import numpy as np #basic math
from statistics import * #stats
import pandas as pd
from pandas.io.formats.style import Styler

nba=pd.read_csv('nbaPO.csv') #read it in  ; or full path: '/content/ex1.csv'

#nba.columns
nba
# nba.plot(kind='scatter', y='FT%', x='Age')
#pd.crosstab(nba["Pos"], nba["AST"]) #too many numbers for a crosstab!
pd.crosstab(nba["Pos"], nba["TRB"])
#pd.crosstab(nba[])


#nba.hist(figsize=(12,8))

TRB,0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,9.0,9.3,9.8,10.0,10.7,10.8,12.4,13.2,14.2,14.3
Pos,,,,,,,,,,,,,,,,,,,,,
C,0,0,0,0,0,0,1,0,1,0,...,0,1,0,1,1,1,1,2,0,1
PF,3,0,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
PG,1,0,0,2,0,4,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
SF,2,1,0,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
SG,3,0,0,2,1,1,3,0,2,1,...,0,0,0,0,0,0,0,0,0,0

In [9]:
import csv
import time, os, sys, re #basics
import zipfile, json, datetime, string 
import matplotlib.pyplot as plt
import numpy as np #basic math
from statistics import * #stats
import pandas as pd
from pandas.io.formats.style import Styler

nba=pd.read_csv('nbaPO.csv') #read it in  ; or full path: '/content/ex1.csv'

#nba.columns
nba
# nba.plot(kind='scatter', y='FT%', x='Age')
#pd.crosstab(nba["Pos"], nba["AST"]) #too many numbers for a crosstab!
pd.crosstab(nba["Pos"], nba["PTS"])
#pd.crosstab(nba[])


#nba.hist(figsize=(12,8))

PTS,0.0,0.1,0.3,0.5,0.6,0.7,0.8,0.9,1.0,1.1,...,23.6,25.2,25.5,25.6,26.3,27.0,27.1,27.4,31.0,31.7
Pos,,,,,,,,,,,,,,,,,,,,,
C,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
PF,4,1,0,0,0,1,1,1,0,0,...,0,0,0,0,1,0,0,0,0,1
PG,3,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,1
SF,1,0,1,1,1,1,2,0,1,1,...,0,0,0,1,0,1,0,1,0,0
SG,4,0,1,0,0,1,0,0,3,1,...,0,1,1,0,0,0,0,0,0,0

After looking at the above 3 crosstabs with NBA playoff data, can see there is a similarity between positions of elite players and those on the low end for their averages.

Shooting Guards and Small Forwards tended to mainly only make a mark big with scoring.

Elite Centers continue to dominate the Total Rebounding averages.

Where as elite Point guards in modern NBA tend to be Scoring and Assiting at a much higher rate. This is unsual compared to early NBA where Point guards were mainly concered with bringing the ball up and assiting the offense, not so much scoring.

This change in where elite dominant player impact could be a result of star player Steph Curry shaping how NBA coaches and players are running their offense. This HUGE change could also be a result to players changing their position all together and could change the way position roles are viewed in todays game.